Repository Field-Passer/newFieldPasser-BE, pull requests merged in 2023-08, with the labels that each got.

#84 feat: 양도시작시간이 지난 게시글 삭제 기능 추가 및 상세조회 응답값 변경, 회원정보 조회 응답값 변경
  src/main/java/com/example/newfieldpasser/NewFieldPasserApplication.java
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/dto/MypageDTO.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#85 refactor: 댓글, 답글 조회 로직 수정
  src/main/java/com/example/newfieldpasser/controller/CommentController.java
  src/main/java/com/example/newfieldpasser/controller/ReplyController.java
  src/main/java/com/example/newfieldpasser/dto/CommentDTO.java
  src/main/java/com/example/newfieldpasser/dto/ReplyDTO.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
  src/main/java/com/example/newfieldpasser/service/ReplyService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#86 refactor: 게시글 등록 시 오류 확인 위해 수정
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Low, Status: Completed, Type: Maintenance

#87 refactor: NPE로 인한 로직 수정
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type : Bug

#88 refactor: NPE 방지를 위한 로직 재수정
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type : Bug

#89 refactor: NPE방지 위한 로직 재수정
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type : Bug

#90 refactor: NPE방지 로직 재수정
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type : Bug

#91 refactor: 게시글 수정 시 파일첨부 로직 수정
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Maintenance

#92 refactor: 게시글 수정 로직 수정
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Maintenance

#93 refactor: 게시글 수정 로직 재수정
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Maintenance

#94 refactor: 게시글 수정 로직 재수정
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Maintenance

#95 refactor: 게시글 수정 로직 재수정
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Maintenance

#96 refactor: 게시글 수정 첨푸파일 필수 아니도록 변경
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Maintenance

#97 ref: querydsl을 이용해서 계층형구조로 댓글 생성 기능 댓글 조회 기능 수정
  src/main/java/com/example/newfieldpasser/controller/CommentController.java
  src/main/java/com/example/newfieldpasser/dto/CommentDTO.java
  src/main/java/com/example/newfieldpasser/entity/Comment.java
  src/main/java/com/example/newfieldpasser/repository/CommentRepository.java
  src/main/java/com/example/newfieldpasser/repository/CommentRepositoryCustom.java
  src/main/java/com/example/newfieldpasser/repository/CommentRepositoryImpl.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
Labels: For: API, Priority: Low, Type: Feature

#98 refactor: 대댓글 본인 작성여부 반환 추가 및 게시글 상세조회 시 관심글 여부 반환
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#99 ref: 생성 조회 기능 주석 처리, reply 관련 삭제
  src/main/java/com/example/newfieldpasser/controller/CommentController.java
  src/main/java/com/example/newfieldpasser/controller/ReplyController.java
  src/main/java/com/example/newfieldpasser/dto/CommentDTO.java
  src/main/java/com/example/newfieldpasser/dto/ReplyDTO.java
  src/main/java/com/example/newfieldpasser/entity/Comment.java
  src/main/java/com/example/newfieldpasser/entity/Reply.java
  src/main/java/com/example/newfieldpasser/exception/reply/ErrorCode.java
  src/main/java/com/example/newfieldpasser/exception/reply/ReplyException.java
  src/main/java/com/example/newfieldpasser/repository/CommentRepositoryImpl.java
  src/main/java/com/example/newfieldpasser/repository/ReplyRepository.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
  src/main/java/com/example/newfieldpasser/service/ReplyService.java
Labels: For: API, Status: In Progress, Type: Feature

#100 ref: 댓글 삭제 기능 구현 및 memberEntity reply 삭제
  src/main/java/com/example/newfieldpasser/entity/Comment.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/repository/CommentRepositoryCustom.java
  src/main/java/com/example/newfieldpasser/repository/CommentRepositoryImpl.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
Labels: For: API, For: Backend, Status: In Progress, Type: Feature

#101 ref: commentDTO.commentResDTO deleteCheck 수정
  src/main/java/com/example/newfieldpasser/dto/CommentDTO.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
Labels: For: API, For: Backend, Status: In Progress, Type: Feature

#102 refactor: 관심글 등록 및 삭제 시 토큰 통해서 멤버 아이디 가져오도록 변경
  src/main/java/com/example/newfieldpasser/controller/WishBoardController.java
  src/main/java/com/example/newfieldpasser/dto/WishBoardDTO.java
  src/main/java/com/example/newfieldpasser/entity/Comment.java
  src/main/java/com/example/newfieldpasser/service/WishBoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#103 refactor: 댓글 생성 시 delete_check false로 들어가도록 변경
  src/main/java/com/example/newfieldpasser/dto/CommentDTO.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#104 ref: @DynamicInsert를 사용해서 deleteCheck default false로 설정,
  src/main/java/com/example/newfieldpasser/dto/CommentDTO.java
  src/main/java/com/example/newfieldpasser/entity/Comment.java
Labels: For: API, For: Backend, Priority: Low, Status: In Progress, Type: Feature

#105 feat: 관리자용 게시글 블라인드 처리 및 해제 기능 구현, 블라인드 게시글만 조회 기능 구현
  src/main/java/com/example/newfieldpasser/controller/AdminController.java
  src/main/java/com/example/newfieldpasser/entity/Board.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#106 refactor: 댓글 조회 시 페이징 처리되지 않는 문제 해결
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/controller/CommentController.java
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/dto/CommentDTO.java
  src/main/java/com/example/newfieldpasser/repository/CommentRepositoryCustom.java
  src/main/java/com/example/newfieldpasser/repository/CommentRepositoryImpl.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: API, Priority: High, Status: Completed, Type : Bug

#107 ref: 댓글 조회 100개씩 나오게 수정
  src/main/java/com/example/newfieldpasser/service/CommentService.java
Labels: For: API, Priority: Low

#108 refactor: 프론트 측의 요청으로 댓글 조회 무한 스크롤 -> 페이지 형식으로 변경
  src/main/java/com/example/newfieldpasser/repository/CommentRepositoryImpl.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#109 feat: 게시글 판매완료 변경 기능 추가
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/entity/Board.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Low, Status: Completed, Type: Feature

#110 feat: memberNickName 누르면 member정보와 boardId,boardtitle 조회
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/MypageDTO.java
  src/main/java/com/example/newfieldpasser/exception/member/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/MemberRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, For: Backend, Priority: Low, Type: Feature

#111 feat: 회원 닉네임 입력하면 회원 정보 조회
  src/main/java/com/example/newfieldpasser/controller/CommentController.java
  src/main/java/com/example/newfieldpasser/exception/comment/ErrorCode.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
Labels: For: API, For: Backend, Priority: Low, Type: Feature

#112 feat: 내가 작성한 글 조회 시 페이징 처리방식 변경
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#113 ref: 아이디 입력하면 회원정보와 작성한 게시글 조회 수정
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/MypageDTO.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, For: Backend, Priority: Low, Type: Feature

#114 refactor: 프론트 측 요청으로 소셜로그인 테스트를 위해 리다이렉트 주소 변경
  src/main/java/com/example/newfieldpasser/jwt/OAuth2MemberSuccessHandler.java
Labels: For: API, Priority: Low, Status: In Progress, Type: Maintenance
