Repository Field-Passer/newFieldPasser-BE, pull requests merged in 2023-07, with the labels that each got.

#64 feat: OAuth2를 사용한 구글 소셜 로그인 기능 구현
  build.gradle
  src/main/java/com/example/newfieldpasser/config/SecurityConfig.java
  src/main/java/com/example/newfieldpasser/dto/OAuth2CustomUser.java
  src/main/java/com/example/newfieldpasser/dto/OAuthAttributes.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/jwt/OAuth2MemberSuccessHandler.java
  src/main/java/com/example/newfieldpasser/service/CustomOAuth2UserService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#65 refactor: 멤버 엔터티 provider 컬럼 추가 및 로그아웃, 회원탈퇴 시 로직 수정
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/dto/OAuthAttributes.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/service/AuthService.java
  src/main/java/com/example/newfieldpasser/service/CustomOAuth2UserService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#66 feat: 네이버 소셜로그인 기능 추가
  src/main/java/com/example/newfieldpasser/config/SecurityConfig.java
  src/main/java/com/example/newfieldpasser/dto/OAuthAttributes.java
  src/main/java/com/example/newfieldpasser/jwt/OAuth2MemberSuccessHandler.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#68 feat: 이메일 인증 기능 구현 및 인증번호 확인 기능 구현
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/service/MailService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#72 refactor: Cookie 관련 설정 변경
  src/main/java/com/example/newfieldpasser/controller/AuthController.java
  src/main/java/com/example/newfieldpasser/service/AuthService.java
Labels: For: API, Priority: Medium, Status: Completed, Type : Bug

#73 refactor: Cookie 설정 재변경
  src/main/java/com/example/newfieldpasser/controller/AuthController.java
  src/main/java/com/example/newfieldpasser/service/AuthService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#74 feat: QueryDSL 사용하여 조건 검색 API 개발
  .idea/compiler.xml
  build.gradle
  src/main/java/com/example/newfieldpasser/config/QuerydslConfiguration.java
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepositoryCustom.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepositoryImpl.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#75 refactor: 회원탈퇴 에러 해결 및 조건검색 파라미터로 배열 받는 것으로 변경
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: API, Priority: High, Status: Completed, Type: Maintenance

#76 ref: 중복 이메일 검사 기능 수정
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
Labels: For: API, For: Backend, Priority: Low, Status: In Progress, Type: Feature

#77 refactor: 조건검색 API 지역리스트 배열 타입 변경
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepositoryCustom.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepositoryImpl.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#79 refactor: boardReq DTO 수정 및 file 파라미터 설정 변경
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/entity/Board.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#80 refactor: boardReqDTO 수정
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Maintenance

#81 refactor: 게시글 생성시각과 수정시각 어노테이션 변경
  src/main/java/com/example/newfieldpasser/NewFieldPasserApplication.java
  src/main/java/com/example/newfieldpasser/entity/Board.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#82 refactor: 애플리케이션 타임존 변경
  src/main/java/com/example/newfieldpasser/NewFieldPasserApplication.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#83 refactor: 타임존 설정 삭제
  src/main/java/com/example/newfieldpasser/NewFieldPasserApplication.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance
