Repository Field-Passer/newFieldPasser-BE, pull requests merged in 2023-06, with the labels that each got.

#4 conf: CI/CD 설정을 위한 테스트 어노테이션 삭제
  src/test/java/com/example/newfieldpasser/NewFieldPasserApplicationTests.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#5 conf: CI/CD 설정을 위한 Dockerfile 추가
  Dockerfile
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#6 conf: CI/CD 테스트
  src/main/java/com/example/newfieldpasser/controller/TestController.java
Labels: For: CI/CD, Priority: Medium, Status: Completed, Type: Maintenance

#7 conf: Dockfile 수정
  Dockerfile
Labels: For: CI/CD, Priority: Low, Status: Completed, Type: Maintenance

#8 conf: 빌드 시 jar파일 하나만 생성되도록 변경 및 Dockerfile 변경
  Dockerfile
  build.gradle
Labels: For: CI/CD, Priority: Low, Status: Completed, Type: Maintenance

#10 conf: Dockfile 수정
  Dockerfile
Labels: For: CI/CD, Priority: Low, Status: Completed, Type: Maintenance

#15 feat: 회원가입 기능 구현, SecurityConfig, WebConfig, Redis 설정 추가
  build.gradle
  src/main/java/com/example/newfieldpasser/config/RedisRepositoryConfig.java
  src/main/java/com/example/newfieldpasser/config/SecurityConfig.java
  src/main/java/com/example/newfieldpasser/config/WebConfig.java
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/dto/AuthDTO.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/exception/member/ErrorCode.java
  src/main/java/com/example/newfieldpasser/exception/member/MemberException.java
  src/main/java/com/example/newfieldpasser/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/example/newfieldpasser/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/newfieldpasser/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/newfieldpasser/jwt/JwtTokenProvider.java
  src/main/java/com/example/newfieldpasser/parameter/Role.java
  src/main/java/com/example/newfieldpasser/repository/MemberRepository.java
  src/main/java/com/example/newfieldpasser/service/MemberDetailsImpl.java
  src/main/java/com/example/newfieldpasser/service/MemberDetailsServiceImpl.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
  src/main/java/com/example/newfieldpasser/service/RedisService.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#18 conf: URL명 수정
  src/main/java/com/example/newfieldpasser/jwt/JwtTokenProvider.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Maintenance

#20 feat: 카테고리 리스트 조회, 지역 리스트 조회 구현
  src/main/java/com/example/newfieldpasser/controller/CategoryController.java
  src/main/java/com/example/newfieldpasser/controller/DistrictController.java
  src/main/java/com/example/newfieldpasser/dto/CategoryDTO.java
  src/main/java/com/example/newfieldpasser/dto/DistrictDTO.java
  src/main/java/com/example/newfieldpasser/repository/CategoryRepository.java
  src/main/java/com/example/newfieldpasser/repository/DistrictRepository.java
  src/main/java/com/example/newfieldpasser/service/CategoryService.java
  src/main/java/com/example/newfieldpasser/service/DistrictService.java
Labels: For: API, Priority: Low, Status: Completed, Type: Feature

#24 feat: 게시글 등록 기능 구현 및 AWS S3 설정
  build.gradle
  src/main/java/com/example/newfieldpasser/config/S3Config.java
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/repository/CategoryRepository.java
  src/main/java/com/example/newfieldpasser/repository/DistrictRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#26 feat: 게시글 상세조회 기능 구현
  src/main/java/com/example/newfieldpasser/config/SecurityConfig.java
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/exception/board/BoardException.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#28 feat: 게시글 수정 기능 구현
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/entity/Board.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#29 feat: 게시글 삭제 기능 구현
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/entity/Board.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#33 feat: 게시글 리스트 조회 기능 구현
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#35 feat: 임시비밀번호 생성, 임시 비밀번호 저장, 이메일 전송
  build.gradle
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/service/MailService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
  src/main/java/com/example/newfieldpasser/vo/MailVo.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Feature

#37 feat: 제목으로 게시글 리스트 검색 기능 구현
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#39 feat: 관심 글 등록 기능 구현
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/controller/WishBoardController.java
  src/main/java/com/example/newfieldpasser/dto/WishBoardDTO.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/repository/WishBoardRepository.java
  src/main/java/com/example/newfieldpasser/service/WishBoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#40 feat: 비밀번호 변경 기능 구현
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/dto/MypageDTO.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Feature

#41 feat: 회원 탈퇴 기능 구현
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/exception/member/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/MemberRepository.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: API, For: Backend, Priority: Medium, Status: In Progress, Type: Feature

#42 feat: 관심 글 조회, 관심 글 삭제 기능 구현
  src/main/java/com/example/newfieldpasser/controller/WishBoardController.java
  src/main/java/com/example/newfieldpasser/dto/WishBoardDTO.java
  src/main/java/com/example/newfieldpasser/entity/WishBoard.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/repository/WishBoardRepository.java
  src/main/java/com/example/newfieldpasser/service/WishBoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#43 feat: 이메일 인증 , 이메일 중복 기능 구현
  src/main/java/com/example/newfieldpasser/controller/MemberController.java
  src/main/java/com/example/newfieldpasser/exception/member/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/MemberRepository.java
  src/main/java/com/example/newfieldpasser/service/MailService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
Labels: For: API, For: Backend, Priority: Medium, Status: In Progress, Type: Feature

#48 feat: 관리자 승격, 사용자로 전환, 문의글 답변 등록, 문의글 전체 조회 기능 구현
  src/main/java/com/example/newfieldpasser/config/SecurityConfig.java
  src/main/java/com/example/newfieldpasser/controller/AdminController.java
  src/main/java/com/example/newfieldpasser/dto/AnswerDTO.java
  src/main/java/com/example/newfieldpasser/entity/Answer.java
  src/main/java/com/example/newfieldpasser/entity/Member.java
  src/main/java/com/example/newfieldpasser/entity/Question.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/exception/member/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/AnswerRepository.java
  src/main/java/com/example/newfieldpasser/repository/QuestionRepository.java
  src/main/java/com/example/newfieldpasser/service/AnswerService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
  src/main/java/com/example/newfieldpasser/service/QuestionService.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#50 feat: 문의글 답변 조회 기능 구현
  src/main/java/com/example/newfieldpasser/controller/QuestionController.java
  src/main/java/com/example/newfieldpasser/dto/AnswerDTO.java
  src/main/java/com/example/newfieldpasser/dto/QuestionDTO.java
  src/main/java/com/example/newfieldpasser/exception/board/ErrorCode.java
  src/main/java/com/example/newfieldpasser/repository/AnswerRepository.java
  src/main/java/com/example/newfieldpasser/service/QuestionService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#53 feat: 날짜 관련 게시글 리스트 조회 기능 구현
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#58 refactor: 게시글 리스트 조회 시 지역은 중복선택 가능하도록 변경
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/dto/DistrictDTO.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: High, Status: Completed, Type: Maintenance

#59 feat: 답글 수정 조회 삭제 기능
  src/main/java/com/example/newfieldpasser/controller/ReplyController.java
  src/main/java/com/example/newfieldpasser/dto/ReplyDTO.java
  src/main/java/com/example/newfieldpasser/entity/Reply.java
  src/main/java/com/example/newfieldpasser/repository/ReplyRepository.java
  src/main/java/com/example/newfieldpasser/service/ReplyService.java
Labels: For: API, For: Backend, Priority: Low, Status: In Progress, Type: Feature

#62 feat: 날짜 관련 검색 기능 추가 구현
  src/main/java/com/example/newfieldpasser/controller/BoardController.java
  src/main/java/com/example/newfieldpasser/repository/BoardRepository.java
  src/main/java/com/example/newfieldpasser/service/BoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature
