Repository Field-Passer/newFieldPasser-BE, pull requests merged in 2023-09, with the labels that each got.

#115 refactor: 소셜 로그인 리다이렉트 주소 배포주소로 재변경
  src/main/java/com/example/newfieldpasser/jwt/OAuth2MemberSuccessHandler.java
Labels: For: API, Priority: Low, Status: Completed, Type: Maintenance

#116 refactor: 내가 작성한 글 조회 성공 메시지 변경 및 관심글 조회, 내가 작성한 댓글 조회 페이지네이션으로 변경
  src/main/java/com/example/newfieldpasser/repository/CommentRepository.java
  src/main/java/com/example/newfieldpasser/repository/WishBoardRepository.java
  src/main/java/com/example/newfieldpasser/service/CommentService.java
  src/main/java/com/example/newfieldpasser/service/MemberService.java
  src/main/java/com/example/newfieldpasser/service/WishBoardService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Maintenance

#117 ref: 회원닉네임 입력하면 회원등급 나오게 수정
  src/main/java/com/example/newfieldpasser/dto/BoardDTO.java
  src/main/java/com/example/newfieldpasser/dto/MypageDTO.java
Labels: For: API, For: Backend, Priority: Low
